server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/identity_service"
    username: root
    password: admin
    # Config logging ( debug -> info -> warn -> error -> fatle)
  #config show banner
  main:
    banner-mode: off

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#
#logging:
#  level:
#    root: WARN